### ISSUE TITLE
trouble to run the program

### ISSUE THREAD

**Issue by facutoledo** [abdeladim-s/whatsapp-msgstore-viewer#1]
Hi, I'm trying to test you program, and cannot make it run. It return the next error:
```
Traceback (most recent call last):
   File "d:\PyProjects\WhatsApp_db_reader\whatsapp-msgstore-viewer-main\main.py", line 148, in <module>
     whatsappMsgstoreViewer().run()
     ^^^^^^^^^^^^^^^^^^^^^^^^
   File "d:\PyProjects\WhatsApp_db_reader\whatsapp-msgstore-viewer-main\main.py", line 90, in __init__
     self.db_version = self.db_versions[0]
```
I have use print(len(self.db_versions)) returning me 0 value. 
```
self.db_versions = []
        for _, name, _ in pkgutil.iter_modules(['dbs']):
            if name != 'abstract_db':
                self.db_versions.append(name)
        print(len(self.db_versions))
        self.db_version = self.db_versions[0]
```

**Comment by abdeladim-s** [comment]
Hi @facutoledo,

I think `pkgutil` cannot see the submodule `dbs` to load the database schema.

I tried to use a different approach to fix it.
Could you please give it a try now ?
