### ISSUE TITLE
object has no attribute 'theme_cls'

### ISSUE THREAD

**Issue by gnu-like** [abdeladim-s/whatsapp-msgstore-viewer#2]
```
[ERROR  ] [whatsappMsgstoreViewer] Error when building app
Traceback (most recent call last):
  File "/home/linux/.local/lib/python3.9/site-packages/kivymd/tools/hotreload/app.py", line 284, in rebuild
    self.approot = self.build_app()
  File "/home/linux/whatsapp-msgstore-viewer/main.py", line 136, in build_app
    controller = screens[name_screen]["controller"](model)
  File "/home/linux/whatsapp-msgstore-viewer/Controller/login_screen.py", line 26, in __init__
    self.view = View.LoginScreen.login_screen.LoginScreenView(controller=self, model=self.model)
  File "/home/linux/whatsapp-msgstore-viewer/View/LoginScreen/login_screen.py", line 125, in __init__
    text_color=self.theme_cls.primary_color,
AttributeError: 'LoginScreenView' object has no attribute 'theme_cls'
 Traceback (most recent call last):
   File "/home/linux/whatsapp-msgstore-viewer/main.py", line 162, in <module>
     whatsappMsgstoreViewer().run()
   File "/home/linux/.local/lib/python3.9/site-packages/kivy/app.py", line 955, in run
     self._run_prepare()
   File "/home/linux/.local/lib/python3.9/site-packages/kivy/app.py", line 925, in _run_prepare
     root = self.build()
   File "/home/linux/.local/lib/python3.9/site-packages/kivymd/tools/hotreload/app.py", line 195, in build
     self.rebuild(first=True)
   File "/home/linux/.local/lib/python3.9/site-packages/kivymd/tools/hotreload/app.py", line 284, in rebuild
     self.approot = self.build_app()
   
```

**Comment by abdeladim-s** [comment]
@gnu-like, it looks like `kivymd` did some update that breaks the app.
Please reinstall the package, I have updated the `requirements.txt` file to use the specific commit hash which is working on my end.

**Comment by gnu-like** [comment]
> @gnu-like, it looks like `kivymd` did some update that breaks the app. Please reinstall the package, I have updated the `requirements.txt` file to use the specific commit hash which is working on my end.
@abdeladim-s thanks, solved
